language: ruby
rvm:
  - 2.6.1

before_install:
  - sudo apt-get install -y build-essential libffi-dev libssl-dev libcurl4-gnutls-dev libxml2-dev
  - npm install
  - npm install -g gulp-cli

install: bundle install

before_script:
  - chmod +x ./bin/cibuild.sh  # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - gulp lint
  - gulp build
  - ./bin/cibuild.sh

# # branch whitelist, only for GitHub Pages
branches:
  only:
    - master
    - /^release\/.*$/

sudo: false # route your build to the container-based infrastructure for a faster build

# caching bundler gem packages will speed up build
cache:
  bundler: true
  directories:
    - node_modules
    - ./bin/tmp/.htmltest

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

