language: ruby
rvm:
  - 2.5.1

before_script:
 - chmod +x ./bin/cibuild.sh  # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./bin/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - develop     # test the development branch
  - release\/(.*) # test every branch which starts with "release/"
  - ISSUE-(.*)/ # test every branch which starts with "ISSUE-"
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - build-essential
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libcurl4-gnutls-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
