language: ruby
rvm:
  - 2.6.1

before_install:
  - npm install
  - npm install -g gulp-cli

install: bundle install

before_script:
- chmod +x ./bin/cibuild.sh  # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - gulp lint
  - gulp build
  - ./bin/cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# branch whitelist, only for GitHub Pages
  branches:
  only:
  - develop     # test the development branch
  - release\/(.*) # test every branch which starts with "release/"
  - page\/(.*) # test every branch which starts with "page/"
  - ISSUE-(.*)/ # test every branch which starts with "ISSUE-"
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - build-essential
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libcurl4-gnutls-dev

sudo: false # route your build to the container-based infrastructure for a faster build
cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
