sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.23.2
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

 before_script:
  - docker-compose build
  - docker-compose run --rm web npm install

script:
  - docker-compose run --rm web gulp build
  - docker-compose run --rm web bin/cibuild.sh

notifications:
  email: false
