dist: trusty
sudo: false # route your build to the container-based infrastructure for a faster build

matrix:
  include:
   - language: node_js
      node_js:
        - 10.15
      before_script:
        - npm install
        - npm install gulp-cli
      cache:
        directories:
          - "node_modules"
      script:
        - gulp lint
        - gulp build
    - language: ruby
      rvm:
        - 2.5.1
      before_script:
        - chmod +x ./bin/cibuild.sh  # or do this locally and commit
      script: ./bin/cibuild.sh
      cache: bundler # caching bundler gem packages will speed up build

# branch whitelist, only for GitHub Pages
  branches:
  only:
  - develop     # test the development branch
  - release\/(.*) # test every branch which starts with "release/"
  - page\/(.*) # test every branch which starts with "page/"
  - ISSUE-(.*)/ # test every branch which starts with "ISSUE-"
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - build-essential
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libcurl4-gnutls-dev

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
