# Name of the site (displayed in the header)
name: demain·il·pleut

# Short bio or description (displayed in the header)
description: Coding & Design for the rainy days

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: https://www.demainilpleut.fr

# Your website logo (usefull for Twitter Cards)
logo: assets/images/logo.png

# Default site encoding
encoding: utf-8

# Number of post to display on the front page
paginate: 4
paginate_path: "/page/:num/"

# Exclude these files from your production _site
exclude:
  - .DS_Store
  - .bundle
  - .bundle-docker
  - .dockerignore
  - .editorconfig
  - .eslintrc.yml
  - .git
  - .github
  - .gitignore
  - .ruby-version
  - .stylelintrc
  - .travis.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Procfile
  - README.md
  - Rakefile
  - bin
  - config.ru
  - docker-compose.yml
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - vendor

# Display drafts
show_drafts: true

# Folders and files to include in the build
include:
  - assets
  - authors
  - styleguide

# Archives configuration
jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layouts:
    category: archives-category
    year: archives-year
    month: archives-month
  permalinks:
    category: /archives/:name/
    year: /archives/:year/
    month: /archives/:year/:month/

# Plugins to include
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
