# Name of the site (displayed in the header)
name: demain·il·pleut

# Short bio or description (displayed in the header)
description: Coding & Design for the rainy days

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: https://www.demainilpleut.fr

# Your website logo (usefull for Twitter Cards)
logo: assets/images/logo.png

# Default site encoding
encoding: utf-8

# Cause a build to fail if there is a YAML syntax error in a page's front matter
strict_front_matter: true

# Markdown options
kramdown:
  input: GFM
  hard_wrap: false

# Number of post to display on the front page
paginate: 4
paginate_path: "/page/:num/"

# Exclude these files from your production _site
exclude:
  - .bundle
  - .bundle-docker
  - .dockerignore
  - .DS_Store
  - .editorconfig
  - .eslintrc.yml
  - .git
  - .github
  - .gitignore
  - .ruby-version
  - .stylelintrc
  - .travis.yml
  - bin
  - config.ru
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - package-lock.json
  - package.json
  - Procfile
  - Rakefile
  - README.md
  - static.json
  - vendor

# Display drafts
show_drafts: true

# Folders and files to include in the build
include:
  - assets
  - authors
  - styleguide

# Archives configuration
jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layouts:
    category: archives-category
    year: archives-year
    month: archives-month
  permalinks:
    category: /archives/:name/
    year: /archives/:year/
    month: /archives/:year/:month/

# Jekyll compose configuration
jekyll_compose:
  draft_default_front_matter:
    excerpt_separator: <!--readmore-->
    layout: post
    title: 'Title goes here'
    published_at:
    categories: []
    permalink: /:title/
    author:
    summary: ''
  post_default_front_matter:
    excerpt_separator: <!--readmore-->
    layout: post
    title: 'Title goes here'
    published_at:
    categories: []
    permalink: /:title/
    author:
    summary: ''
    published: false

defaults:
  -
    scope:
      path: "assets/**/*"
    values:
      sitemap: false

# Plugins to include
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-compose
